name: leanto

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend:/usr/share/caddy
    environment:
      - DOMAIN=${DOMAIN}
  api:
    build: ./api
    restart: unless-stopped
    environment:
      - DB_CONN=mongodb://root:${DB_ROOT_PASSWORD}@db
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

volumes:
  caddy-config:
  caddy-data:
  db-data:
